
version: '3.8'
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: sentinel-metrics-DECATHLON-DIGITAL
    ports:
      - "9100:9100"
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.0
    container_name: sentinel-logs-DECATHLON-DIGITAL
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    restart: always
